<<<<<<< HEAD
# Generated by Django 4.2.13 on 2024-07-13 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 5.0.6 on 2024-09-19 14:02

import django.utils.timezone
from django.db import migrations, models
>>>>>>> 369378f (first commit)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('vehicleApp', '0005_vehicle_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 369378f (first commit)
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=255)),
                ('plate_number', models.CharField(max_length=255, unique=True)),
<<<<<<< HEAD
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleApp.vehicle')),
=======
                ('national_id_card', models.BinaryField(blank=True, null=True)),
                ('driving_license', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
>>>>>>> 369378f (first commit)
            ],
        ),
    ]
