# Generated by Django 4.2.13 on 2024-07-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='driving_license',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='national_id_card',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
