# Generated by Django 4.2.13 on 2024-07-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancerApp', '0002_freelancer_driving_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
