<<<<<<< HEAD
# Generated by Django 4.2.13 on 2024-07-23 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 5.0.6 on 2024-09-19 16:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
>>>>>>> 369378f (first commit)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('orderApp', '0002_order_status_order_type'),
        ('vehicleApp', '0005_vehicle_created_by'),
=======
>>>>>>> 369378f (first commit)
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
<<<<<<< HEAD
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='orderApp.order')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleApp.vehicle')),
=======
>>>>>>> 369378f (first commit)
            ],
        ),
    ]
