# Generated by Django 5.0.6 on 2024-09-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discountApp', '0001_initial'),
        ('orderApp', '0001_initial'),
        ('vehicleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='orderApp.order'),
        ),
        migrations.AddField(
            model_name='discountorder',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleApp.vehicle'),
        ),
    ]
