# Generated by Django 5.0.7 on 2024-08-15 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderApp', '0004_alter_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(default='', max_length=255)),
                ('amount', models.CharField(default='', max_length=255)),
                ('provider', models.CharField(default='', max_length=15)),
                ('status', models.CharField(default='', max_length=10)),
                ('kind', models.CharField(default='', max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orderApp.order')),
            ],
        ),
    ]
