# Generated by Django 4.2.13 on 2024-07-23 02:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelancerApp', '0003_alter_freelancer_status'),
        ('orderApp', '0002_order_status_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelancerApp.freelancer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderApp.order')),
            ],
        ),
    ]
