<<<<<<< HEAD
# Generated by Django 4.2.13 on 2024-07-30 03:57

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.0.6 on 2024-09-19 14:02

from django.db import migrations, models
>>>>>>> 369378f (first commit)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('vehicleApp', '0005_vehicle_created_by'),
=======
>>>>>>> 369378f (first commit)
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='vehicleApp.vehicle')),
=======
>>>>>>> 369378f (first commit)
            ],
        ),
    ]
