# Generated by Django 5.0.6 on 2024-09-19 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trackingApp', '0001_initial'),
        ('vehicleApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='vehicleApp.vehicle'),
        ),
    ]
