# Generated by Django 4.2.13 on 2024-07-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_customuser_login_count_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='login_count',
        ),
    ]
