# Generated by Django 5.0.7 on 2024-09-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_remove_customuser_login_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('freelancer', 'Freelancer'), ('shop_owner', 'Shop Owner'), ('customer', 'Customer')], max_length=20),
        ),
    ]
