<<<<<<< HEAD
# Generated by Django 4.2.13 on 2024-07-12 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.0.6 on 2024-09-19 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
>>>>>>> 369378f (first commit)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus'), ('van', 'Van')], max_length=50)),
                ('total_weight_to_carry', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50)),
                ('total_weight_to_carry', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
>>>>>>> 369378f (first commit)
            ],
        ),
    ]
