# Generated by Django 4.2.13 on 2024-07-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('bus', 'Bus'), ('van', 'Van'), ('motor', 'Motor')], max_length=50),
        ),
    ]
