# Generated by Django 4.2.13 on 2024-07-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleApp', '0003_alter_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
