<<<<<<< HEAD
# Generated by Django 4.2.13 on 2024-07-18 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
=======
# Generated by Django 5.0.6 on 2024-09-19 16:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
>>>>>>> 369378f (first commit)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('vehicleApp', '0005_vehicle_created_by'),
=======
        ('vehicleApp', '0001_initial'),
>>>>>>> 369378f (first commit)
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
<<<<<<< HEAD
=======
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7)),
                ('payment_status', models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending')], default='pending', max_length=10)),
>>>>>>> 369378f (first commit)
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='vehicleApp.vehicle')),
            ],
        ),
<<<<<<< HEAD
=======
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider', models.CharField(max_length=50)),
                ('kind', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orderApp.order')),
            ],
        ),
>>>>>>> 369378f (first commit)
    ]
