# Generated by Django 4.2.13 on 2024-07-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_order_status_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
