# Generated by Django 4.2.13 on 2024-07-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('successful', 'Successful'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
